name: flutter_persistance_hive
description: "A new Flutter project or local persistence using Hive."
publish_to: 'none'
version: 1.0.0+1
build_number: 0.1

environment:
  sdk: ^3.6.0-55.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  package_info_plus: ^8.0.2

  # Hive dependencies
  hive: ^2.2.3
  hive_flutter: ^1.1.0



  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Needed for generating the TypeAdapter
  hive_generator: ^1.1.3
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
